[package]
name = "jodin-rs-vm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
strict = []

[dependencies]
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
byteorder = "1.4.3"
bitfield = "0.13.2"