mode: auto
defaultBranch: 'develop'
autoCloseIssue: true
branches:
  - label: feature
    prefix: 'feature/${assignee.login}/'
  - label: bug
    prefex: 'bugfix/${assignee.login}/'
branch: '/issue-${issue.id}-${issue.title,}'
