mode: chatops
defaultBranch: 'develop'
autoCloseIssue: true
branches:
  - label: feature
    prefix: 'feature/${assignee.login}/'
  - label: bug
    prefex: 'bugfix/${assignee.login}/'
branchName: 'issue-${issue.id}-${issue.title,}'
