# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[workspace]
members = [
    "jodin-rs-vm",
    "jodin-asm-derive",
    "jodinc",
    "jodin-tests",
    "jodin-common"
]

