[package]
name = "jodin-asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.13.2"
byteorder = "1.4.3"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"