[package]
name = "jodin-tests"
version = "0.1.0"
edition = "2021"


[dependencies]
jodin-common = { path = "../jodin-common" }
jodinc = { path = "../jodinc" }
jodin-rs-vm= { path = "../jodin-rs-vm" }
log = "0.4.14"


