[package]
name = "jodin-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jodin-asm = { path = "../jodin-asm" }
jodinc = { path = "../jodinc" }
jodin-rs-vm= { path = "../jodin-rs-vm" }
