name: Document Rust

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Documentation
      run: cargo doc --workspace --no-deps --verbose --target-dir "docs"
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update Documentation"
        file_pattern: docs/*
        
        
