name: Rust Check

on:
  push:
    branches:
      - '!main'
      - '!develop'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check --workspace --verbose
