name: Rust Release
on:
  workflow_run:
    workflows:
      - "Stage Develop Changes"
    types:
      - completed


env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run lint
        run: cargo check --workspace --features strict

  document:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Documentation
        run: cargo doc --workspace --no-deps --verbose --target-dir "docs"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Documentation"
          file_pattern: docs/*

  push_to_main:
    needs: document
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge staging-> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: main
          github_token: ${{ github.token }}


  create_release:
    needs: push_to_main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

    
