name: Rust Check

on:
  pull_request:
    branches: [ develop, main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check --workspace --verbose
      id: check
    - name: Test
      run: cargo test --workspace --verbose
      id: test

