name: Rust Check

on:
  push:
    branches-ignore:
      - master
      - staging
      - develop

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Awarnings

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Check
      run: cargo check --workspace --verbose
