name: Rust Test

on:
  push:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Awarnings

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test
        run: cargo test --workspace --verbose
