name: Rust Test

on:
  pull_request:
    branches: [ develop, staging ]
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --workspace --verbose
