name: Stage Develop Changes

on:
  workflow_run:
    workflows:
      - "Rust Test"
    branches: [ develop ]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: to_stage
          conclusion: ${{ job.status }}
      - uses: actions/checkout@master
      - name: Merge develop-> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: staging
          github_token: ${{ github.token }}